network: network.c ../imageReader/imageReader.c
	gcc -Wall -Wextra -o network network.c ../imageReader/imageReader.c -I../imageReader -lm `pkg-config --cflags --libs gtk+-3.0`


clean:
	rm -f network
.:	